name: school_management_system_teacher_app
description: A new Flutter project.

publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  flutter_svg: ^2.1.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  skeletonizer: ^1.4.3
  flutter_staggered_animations: ^1.1.1
  syncfusion_flutter_datepicker: ^29.1.38
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_t.png"
  image_path_ios: "assets/images/app_icon_t.png"
  image_path_android: "assets/images/app_icon_t.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/province.json
    - assets/data/district.json
    - assets/data/commune.json
    - assets/data/village.json
    - assets/images/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/logo/
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/images/teacher_management/

  fonts:
    - family: AKbalthomFreedomPlus
      fonts:
        - asset: assets/fonts/akbalthom-freedom-plus.ttf

    - family: NotoSerifKhmer
      fonts:
        - asset: assets/fonts/NotoSerifKhmer/NotoSerifKhmer-VariableFont_wdth,wght.ttf

    - family: Moul
      fonts:
        - asset: assets/fonts/moul/Moul-Regular.ttf

    - family: Suwannaphum
      fonts:
        - asset: assets/fonts/suwannaphum/Suwannaphum-Black.ttf
        - asset: assets/fonts/suwannaphum/Suwannaphum-Bold.ttf
        - asset: assets/fonts/suwannaphum/Suwannaphum-Light.ttf
        - asset: assets/fonts/suwannaphum/Suwannaphum-Regular.ttf
        - asset: assets/fonts/suwannaphum/Suwannaphum-Thin.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
        - asset: assets/fonts/inter/Inter_18pt-BlackItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_18pt-BoldItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter_18pt-ExtraLightItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Italic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
        - asset: assets/fonts/inter/Inter_18pt-LightItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_18pt-MediumItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
        - asset: assets/fonts/inter/Inter_18pt-ThinItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
        - asset: assets/fonts/inter/Inter_24pt-BlackItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_24pt-BoldItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_24pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter_24pt-ExtraLightItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
        - asset: assets/fonts/inter/Inter_24pt-LightItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_24pt-MediumItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_24pt-SemiBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_24pt-Thin.ttf
        - asset: assets/fonts/inter/Inter_24pt-ThinItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Black.ttf
        - asset: assets/fonts/inter/Inter_28pt-BlackItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
        - asset: assets/fonts/inter/Inter_28pt-BoldItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter_28pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter_28pt-ExtraLightItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Italic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Light.ttf
        - asset: assets/fonts/inter/Inter_28pt-LightItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_28pt-MediumItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_28pt-SemiBoldItalic.ttf
        - asset: assets/fonts/inter/Inter_28pt-Thin.ttf
        - asset: assets/fonts/inter/Inter_28pt-ThinItalic.ttf

    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/Kantumruy-Pro-khmer-100-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-100-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-200-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-200-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-300-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-300-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-400-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-400-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-500-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-500-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-600-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-600-normal.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-700-italic.ttf
        - asset: assets/fonts/Kantumruy-Pro-khmer-700-normal.ttf
